### ISSUE TITLE
**USER MODEL**

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Lepre-Track#5]
Data will be stored in firebase in a JSON format. We must layout the USER model carefully so that all user data is rendered without errors across our site.

Initial user model - Please assist as this is key to the entire application: 

const user = {
  id: 10,
  userName: "tommy",
  createdAt: "datestring",
  email: "tommy@gmail.com",
  diet: {
    isVegan: false,
    isVeggie: false,
    redMeatConsumption: 10,
    localProduce: 10,
  },
  recyling: {
    electic: 0,
    plastic: 50,
    paper: 100,
  },
  houseEnergy: {
    electrictiy: 10,
    gas: 10,
    oil: 10,
    coal: 10,
    wood: 10,
    solar: 10,
    isInsulation: true,
  },
  transport: {
    flightsPerYear: 10,
    flightDistanceEst: 10,
    carMilagePerYear: 10,
    vehicle: "car",
    isElectric: false,
    travelPercentKM: {
      cyling: 10,
      bus: 10,
      rail: 10,
      car: 60,
      walking: 10,
    },
  },
  activity: {
    treeplanting: true,
    volunteering: true,
    donation: 100,
  },
};

**Comment by Shane-Donlon** [comment]
Resolved
