### ISSUE TITLE
Research - Recyling

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Lepre-Track#9]
In order to better understand how people can impact the earth and create a greener tomorrow we must understand recycling impact.

Research the effect of recycling (Cardboard, Paper, Electric ) and what impact it has. We will create a basic algo for determining percentage of 1-100 based on these calculations.

**Comment by adammkeane** [comment]
**recycling research**
-do you recycle your paper, glass, plastic and metals?

-if you recycle all of those, you save 61kg of co2 emission per month. Average US person’s packaging waste per month is 38kg. The difference between making new packaging from scratch and recycling the used packaging to be used again is 61kg.. Source: https://changeit.app/blog/recycle-matters/

-for food waste, irish estimate is 52 kg of food waste per person per year (source: https://www.epa.ie/publications/circular-economy/resources/nature-and-extent-update-15th-June.pdf)

-per kg of food waste, your carbon footprint increases by 0.7kg. If you put all that into your compost bin or make your own compost out of it, you will reduce your carbon footprint to 0.5kg per kg of food waste (a saving 0.2kg co2 emissions).
(source: https://8billiontrees.com/carbon-offsets-credits/carbon-footprint-recycling/)

**Comment by adammkeane** [comment]
if no recycling, the above average packaging waste will increase your co2 emissions by:
- Total: 105.9kg per month
- Paper + card = 20.9kg per month
- Plastic = 19.1kg per month
- metals = 63kg per month
- glass = 2.9kg per month
 (source: combined above sources)

if no recycling, the above average food will increase your co2 emissions by:
- Total: 3kg per month

**summary**
- No recycling = 108.9kg co2 emissions per month.
- Recycling all categories = 50.1kg co2 emissions per month (2.2kg (food) + 47.9kg (packaging))
- Bigger picture: Average irish person’s co2 emissions are 1083.3kg per month. Recycling plays a relatively small role in reducing a person’s emissions.

**Comment by Shane-Donlon** [comment]
Implemented as planned
